window.REPOSITORIES_DATA = [
  {
    "id": "REP-001",
    "nombre": "Ahira – Archivo Histórico de Revistas Argentinas",
    "nombre_alternativo": "AHIRA",
    "url": "https://www.ahira.com.ar",
    "url_alternativa": "NA",
    "tipo": "archivo",
    "alcance": "general",
    "especializacion": "revistas culturales",
    "tipos_publicacion": "revistas;suplementos;magazines",
    "volumen_aprox": "~120 títulos",
    "periodo_desde": "1896",
    "periodo_hasta": "2021",
    "idiomas": "español",
    "ciudad": "Buenos Aires",
    "pais": "Argentina",
    "latitud": "-34.6037",
    "longitud": "-58.3816",
    "cobertura_geografica": "Argentina",
    "accesibilidad": "abierta",
    "visualizacion": "PDF;visor propio",
    "descarga": "sí",
    "ocr": "parcial",
    "api": "no",
    "licencia": "dominio público; derechos reservados",
    "calidad_digitalizacion": "alta",
    "interoperabilidad": "desconocida",
    "institucion": "Universidad de Buenos Aires",
    "tipo_institucion": "grupo de investigación",
    "financiamiento": "académico",
    "temas_dominantes": "literatura;arte;política",
    "contacto": "contacto@ahira.com.ar",
    "fecha_relevamiento": "2026-06-23",
    "estado_enlace": "activo",
    "notas": "Colección curada con estudios críticos",
    "images": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-001.webp"
    ],
    "thumbnails": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-001-thumb.webp"
    ]
  },
  {
    "id": "REP-002",
    "nombre": "Hemeroteca Digital – Biblioteca Nacional de España",
    "nombre_alternativo": "BNE",
    "url": "https://hemerotecadigital.bne.es",
    "url_alternativa": "NA",
    "tipo": "hemeroteca digital",
    "alcance": "general",
    "especializacion": "",
    "tipos_publicacion": "periódicos;revistas culturales;magazines",
    "volumen_aprox": "~2000 títulos",
    "periodo_desde": "1683",
    "periodo_hasta": "1960",
    "idiomas": "español;catalán;euskera",
    "ciudad": "Madrid",
    "pais": "España",
    "latitud": "40.4168",
    "longitud": "-3.7038",
    "cobertura_geografica": "España",
    "accesibilidad": "abierta",
    "visualizacion": "JPG;PDF",
    "descarga": "sí",
    "ocr": "sí",
    "api": "sí",
    "licencia": "dominio público",
    "calidad_digitalizacion": "alta",
    "interoperabilidad": "OAI-PMH",
    "institucion": "Biblioteca Nacional de España",
    "tipo_institucion": "biblioteca nacional",
    "financiamiento": "público",
    "temas_dominantes": "literatura;política;cine",
    "contacto": "info@bne.es",
    "fecha_relevamiento": "2026-06-23",
    "estado_enlace": "activo",
    "notas": "Colección de revistas españolas",
    "images": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-002.webp"
    ],
    "thumbnails": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-002-thumb.webp"
    ]
  },
  {
    "id": "REP-003",
    "nombre": "América Lee - Cedinci",
    "nombre_alternativo": "AméricaLee",
    "url": "https://americalee.cedinci.org/ ",
    "url_alternativa": "NA",
    "tipo": "archivo",
    "alcance": "específico",
    "especializacion": "revistas de izquierda",
    "tipos_publicacion": "revistas; periódicos;suplementos;boletines",
    "volumen_aprox": "~300 títulos",
    "periodo_desde": "1863",
    "periodo_hasta": "2011",
    "idiomas": "español",
    "ciudad": "Buenos Aires",
    "pais": "Argentina",
    "latitud": "-34.6037",
    "longitud": "-58.3816",
    "cobertura_geografica": "Latinoamérica",
    "accesibilidad": "abierta",
    "visualizacion": "PDF;visor propio",
    "descarga": "sí",
    "ocr": "sí",
    "api": "no",
    "licencia": "dominio público; derechos reservados",
    "calidad_digitalizacion": "alta",
    "interoperabilidad": "Dublin Core",
    "institucion": "Centro de Documentación e Investigación de la Cultura de Izquierdas (CeDInCI)",
    "tipo_institucion": "otra",
    "financiamiento": "mixto",
    "temas_dominantes": "literatura;arte;política",
    "contacto": "americalee@cedinci.org",
    "fecha_relevamiento": "2026-06-24",
    "estado_enlace": "activo",
    "notas": "Colección curada con estudios críticos, índices razonados y buscador",
    "images": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-003.webp"
    ],
    "thumbnails": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-003-thumb.webp"
    ]
  },
  {
    "id": "REP-004",
    "nombre": "Digital Library of the Caribbean - Revistas",
    "nombre_alternativo": "dLOC",
    "url": "https://www.dloc.com/results?filter=type:Revistas",
    "url_alternativa": "https://www.dloc.com/",
    "tipo": "biblioteca digital",
    "alcance": "general",
    "especializacion": "",
    "tipos_publicacion": "revistas;periódicos;suplementos;boletines",
    "volumen_aprox": "~90 títulos",
    "periodo_desde": "1838",
    "periodo_hasta": "2024",
    "idiomas": "español",
    "ciudad": "Miami",
    "pais": "Estados Unidos",
    "latitud": "25.7617",
    "longitud": "-80.1918",
    "cobertura_geografica": "Caribe",
    "accesibilidad": "abierta",
    "visualizacion": "JP2;PDF;visor propio",
    "descarga": "sí",
    "ocr": "sí",
    "api": "sí",
    "licencia": "dominio público; derechos reservados",
    "calidad_digitalizacion": "alta",
    "interoperabilidad": "OAI-PMH",
    "institucion": "Association of Caribbean University Research and Institutional Libraries (ACURIL)",
    "tipo_institucion": "otra",
    "financiamiento": "desconocido",
    "temas_dominantes": "",
    "contacto": "dLOC@uflib.ufl.edu",
    "fecha_relevamiento": "2026-07-01",
    "estado_enlace": "activo",
    "notas": "Subcolección de revistas publicadas en los países caribeños. Recoge digitalizaciones de distintas instituciones aliadas. La colección de periódicos es más amplia.",
    "images": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-004.webp"
    ],
    "thumbnails": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-004-thumb.webp"
    ]
  },
  {
    "id": "REP-005",
    "nombre": "Revistas de la Edad de Plata",
    "nombre_alternativo": "NA",
    "url": "http://www.edaddeplata.org/revistas_edaddeplata/",
    "url_alternativa": "NA",
    "tipo": "proyecto académico",
    "alcance": "específico",
    "especializacion": "revistas culturales",
    "tipos_publicacion": "revistas",
    "volumen_aprox": "32 títulos",
    "periodo_desde": "1917",
    "periodo_hasta": "1939",
    "idiomas": "español",
    "ciudad": "Madrid",
    "pais": "España",
    "latitud": "40.4168",
    "longitud": "-3.7038",
    "cobertura_geografica": "España",
    "accesibilidad": "abierta",
    "visualizacion": "JPG;visor propio; transcripciones",
    "descarga": "parcial",
    "ocr": "no",
    "api": "no",
    "licencia": "dominio público",
    "calidad_digitalizacion": "media",
    "interoperabilidad": "desconocida",
    "institucion": "La Residencia de Estudiantes",
    "tipo_institucion": "particular",
    "financiamiento": "público",
    "temas_dominantes": "literatura;arte",
    "contacto": "webmaster@edaddeplata.net",
    "fecha_relevamiento": "2026-07-01",
    "estado_enlace": "activo",
    "notas": "Colección de revistas de la Edad de Plata, con transcripción y visualización interactiva.",
    "images": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-005.webp"
    ],
    "thumbnails": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-005-thumb.webp"
    ]
  },
  {
    "id": "REP-006",
    "nombre": "Biblioteca Virtual de Prensa Histórica",
    "nombre_alternativo": "BVPH",
    "url": "https://prensahistorica.mcu.es/es/inicio/inicio.do",
    "url_alternativa": "https://prensahistorica.mcu.es/arce/es/micrositios/inicio.do",
    "tipo": "biblioteca digital",
    "alcance": "general",
    "especializacion": "",
    "tipos_publicacion": "revistas;periódicos",
    "volumen_aprox": "~4000 títulos",
    "periodo_desde": "1730",
    "periodo_hasta": "2025",
    "idiomas": "español;catalán",
    "ciudad": "Madrid",
    "pais": "España",
    "latitud": "40.4168",
    "longitud": "-3.7038",
    "cobertura_geografica": "Iberomamérica",
    "accesibilidad": "abierta",
    "visualizacion": "JPG;PDF;visor propio",
    "descarga": "sí",
    "ocr": "sí",
    "api": "no",
    "licencia": "dominio público; derechos reservados",
    "calidad_digitalizacion": "alta",
    "interoperabilidad": "OAI-PMH",
    "institucion": "Ministerio de Cultura de España",
    "tipo_institucion": "otra",
    "financiamiento": "público",
    "temas_dominantes": "literatura;arte;política",
    "contacto": "info.bvph@cultura.gob.es",
    "fecha_relevamiento": "2026-07-01",
    "estado_enlace": "activo",
    "notas": "Portal de revistas iberomericanas, principalmente españolas, con distintas colecciones prensa temáticas.",
    "images": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-006.webp"
    ],
    "thumbnails": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-006-thumb.webp"
    ]
  },
  {
    "id": "REP-007",
    "nombre": "Arxiu de Revistes Catalanes Antigues",
    "nombre_alternativo": "ARCA",
    "url": "https://arca.bnc.cat/arcabib_pro/es/inicio/inicio.do",
    "url_alternativa": "NA",
    "tipo": "hemeroteca digital",
    "alcance": "específico",
    "especializacion": "revistas catalanas",
    "tipos_publicacion": "revistas",
    "volumen_aprox": "85 títulos",
    "periodo_desde": "1771",
    "periodo_hasta": "2005",
    "idiomas": "español;catalán",
    "ciudad": "Barcelona",
    "pais": "España",
    "latitud": "41.3851",
    "longitud": "2.1734",
    "cobertura_geografica": "España",
    "accesibilidad": "abierta",
    "visualizacion": "JPG;PDF;visor propio",
    "descarga": "sí",
    "ocr": "sí",
    "api": "no",
    "licencia": "dominio público; derechos reservados",
    "calidad_digitalizacion": "alta",
    "interoperabilidad": "OAI-PMH",
    "institucion": "Biblioteca de Catalunya",
    "tipo_institucion": "biblioteca",
    "financiamiento": "público",
    "temas_dominantes": "literatura;arte;política",
    "contacto": "arca@bnc.cat",
    "fecha_relevamiento": "2026-07-01",
    "estado_enlace": "activo",
    "notas": "Portal cooperativo de publicaciones periódicas representativas de la cultura y sociedad catalana.",
    "images": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-007.webp"
    ],
    "thumbnails": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-007-thumb.webp"
    ]
  },
  {
    "id": "REP-008",
    "nombre": "Biblioteca Virtural Miguel de Cervantes - Hemeroteca",
    "nombre_alternativo": "BVMC",
    "url": "https://www.cervantesvirtual.com/portales/hemeroteca/",
    "url_alternativa": "https://www.cervantesvirtual.com/",
    "tipo": "hemeroteca digital",
    "alcance": "general",
    "especializacion": "",
    "tipos_publicacion": "revistas",
    "volumen_aprox": "~660 títulos",
    "periodo_desde": "1791",
    "periodo_hasta": "2006",
    "idiomas": "español;catalán;gallego;",
    "ciudad": "Alicante",
    "pais": "España",
    "latitud": "38.3452",
    "longitud": "-0.4815",
    "cobertura_geografica": "Iberomamérica",
    "accesibilidad": "abierta",
    "visualizacion": "PDF; HTML",
    "descarga": "sí",
    "ocr": "sí",
    "api": "no",
    "licencia": "dominio público; derechos reservados",
    "calidad_digitalizacion": "alta",
    "interoperabilidad": "OAI-PMH",
    "institucion": "Univesidad de Alicante",
    "tipo_institucion": "universidad",
    "financiamiento": "público",
    "temas_dominantes": "literatura;arte;política;historia",
    "contacto": "bibliotecario@cervantesvirtual.com",
    "fecha_relevamiento": "2026-07-01",
    "estado_enlace": "activo",
    "notas": "Subportal de la BVMC dedicado a publicaciones periódicas publicadas en España y América. Ofrece datos abiertos enlazados (RDF) y un Enpoint de consulta SPARQL.",
    "images": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-008.webp"
    ],
    "thumbnails": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-008-thumb.webp"
    ]
  },
  {
    "id": "REP-009",
    "nombre": "Biblioteca Digital de la Comunidad de Madrid - Hemeroteca",
    "nombre_alternativo": "NA",
    "url": "https://bibliotecavirtualmadrid.comunidad.madrid/bvmadrid_publicacion/es/es/publicaciones/listar_cabeceras.do",
    "url_alternativa": "https://bibliotecavirtualmadrid.comunidad.madrid/bvmadrid_publicacion/es/inicio/inicio.do",
    "tipo": "hemeroteca digital",
    "alcance": "general",
    "especializacion": "revistas madrileñas",
    "tipos_publicacion": "revistas;periódicos;boletines",
    "volumen_aprox": "~280 títulos",
    "periodo_desde": "1707",
    "periodo_hasta": "2018",
    "idiomas": "español",
    "ciudad": "Madrid",
    "pais": "España",
    "latitud": "40.4168",
    "longitud": "-3.7038",
    "cobertura_geografica": "España",
    "accesibilidad": "abierta",
    "visualizacion": "JPG;PDF;visor propio",
    "descarga": "sí",
    "ocr": "no",
    "api": "no",
    "licencia": "dominio público; derechos reservados",
    "calidad_digitalizacion": "alta",
    "interoperabilidad": "OAI-PMH",
    "institucion": "Biblioteca Regional de Madrid",
    "tipo_institucion": "biblioteca",
    "financiamiento": "público",
    "temas_dominantes": "literatura;arte;política;sociedad",
    "contacto": "procesos.digitales@madrid.org",
    "fecha_relevamiento": "2026-07-01",
    "estado_enlace": "activo",
    "notas": "Colección de revistas y periódicos editadas en Madrid.",
    "images": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-009.webp"
    ],
    "thumbnails": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-009-thumb.webp"
    ]
  },
  {
    "id": "REP-010",
    "nombre": "Biblioteca Nacional Digital - Hemeroteca",
    "nombre_alternativo": "NA",
    "url": "https://www.bibliotecanacionaldigital.gob.cl/bnd/630/w3-channel.html",
    "url_alternativa": "",
    "tipo": "hemeroteca digital",
    "alcance": "general",
    "especializacion": "",
    "tipos_publicacion": "revistas",
    "volumen_aprox": "128 títulos",
    "periodo_desde": "1851",
    "periodo_hasta": "1946",
    "idiomas": "español",
    "ciudad": "Santiago de Chile",
    "pais": "Chile",
    "latitud": "-33.4489",
    "longitud": "-70.6693",
    "cobertura_geografica": "Chile",
    "accesibilidad": "mixta",
    "visualizacion": "PDF;visor propio",
    "descarga": "parcial",
    "ocr": "sí",
    "api": "no",
    "licencia": "dominio público; derechos reservados",
    "calidad_digitalizacion": "alta",
    "interoperabilidad": "OAI-PMH",
    "institucion": "Biblioteca Nacional de Chile",
    "tipo_institucion": "biblioteca nacional",
    "financiamiento": "público",
    "temas_dominantes": "",
    "contacto": "Formulario",
    "fecha_relevamiento": "2026-07-01",
    "estado_enlace": "activo",
    "notas": "Colección de revistas chilenas.",
    "images": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-010.webp"
    ],
    "thumbnails": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-010-thumb.webp"
    ]
  },
  {
    "id": "REP-011",
    "nombre": "Memoria Chilena",
    "nombre_alternativo": "NA",
    "url": "https://www.memoriachilena.gob.cl/602/w3-propertyvalue-147129.html",
    "url_alternativa": "https://www.memoriachilena.gob.cl/602/w3-channel.html",
    "tipo": "portal agregador",
    "alcance": "general",
    "especializacion": "",
    "tipos_publicacion": "revistas",
    "volumen_aprox": "~545 títulos",
    "periodo_desde": "",
    "periodo_hasta": "",
    "idiomas": "español",
    "ciudad": "Santiago de Chile",
    "pais": "Chile",
    "latitud": "-33.4489",
    "longitud": "-70.6693",
    "cobertura_geografica": "Chile",
    "accesibilidad": "abierta",
    "visualizacion": "PDF;visor propio",
    "descarga": "sí",
    "ocr": "sí",
    "api": "no",
    "licencia": "dominio público",
    "calidad_digitalizacion": "alta",
    "interoperabilidad": "OAI-PMH",
    "institucion": "Biblioteca Nacional de Chile",
    "tipo_institucion": "biblioteca nacional",
    "financiamiento": "público",
    "temas_dominantes": "",
    "contacto": "Formulario",
    "fecha_relevamiento": "2026-07-01",
    "estado_enlace": "activo",
    "notas": "Colección de revistas con estudios dedicados, contextualizadas y de interés para la construcción de la historia cultural chilena.",
    "images": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-011.webp"
    ],
    "thumbnails": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-011-thumb.webp"
    ]
  },
  {
    "id": "REP-012",
    "nombre": "Hemeroteca Digital Nacional de México",
    "nombre_alternativo": "HDNM",
    "url": "https://hndm.iib.unam.mx/index.php/es/",
    "url_alternativa": "NA",
    "tipo": "hemeroteca digital",
    "alcance": "general",
    "especializacion": "",
    "tipos_publicacion": "revistas;periódicos;gacetas;suplementos;boletines;historietas",
    "volumen_aprox": "~1189 títulos",
    "periodo_desde": "1722",
    "periodo_hasta": "2010",
    "idiomas": "español",
    "ciudad": "Ciudad de México",
    "pais": "México",
    "latitud": "19.4326",
    "longitud": "-99.1332",
    "cobertura_geografica": "México",
    "accesibilidad": "mixta",
    "visualizacion": "PDF;visor propio",
    "descarga": "sí",
    "ocr": "parcial",
    "api": "no",
    "licencia": "dominio público; derechos reservados",
    "calidad_digitalizacion": "media",
    "interoperabilidad": "Dublin Core",
    "institucion": "Universidad Nacional Autónoma de México (UNAM)",
    "tipo_institucion": "universidad",
    "financiamiento": "desconocido",
    "temas_dominantes": "sociedad;política;literatura;arte",
    "contacto": "recursosdigitaleshnm@unam.mx",
    "fecha_relevamiento": "2026-07-01",
    "estado_enlace": "activo",
    "notas": "Colecciones de publicaciones periódicas históricas y contemporáneas. Hace parte del proyecto Oceanic Exchanged. ",
    "images": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-012.webp"
    ],
    "thumbnails": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-012-thumb.webp"
    ]
  },
  {
    "id": "REP-013",
    "nombre": "Anáforas. Publicaciones periódicas del Uruguay",
    "nombre_alternativo": "NA",
    "url": "https://anaforas.fic.edu.uy/jspui/handle/123456789/13",
    "url_alternativa": "NA",
    "tipo": "repositorio institucional",
    "alcance": "general",
    "especializacion": "",
    "tipos_publicacion": "revistas;periódicos;historietas;fanzines",
    "volumen_aprox": "~1067 títulos",
    "periodo_desde": "1807",
    "periodo_hasta": "2025",
    "idiomas": "español",
    "ciudad": "Montevideo",
    "pais": "Uruguay",
    "latitud": "-34.9011",
    "longitud": "-56.1645",
    "cobertura_geografica": "Uruguay",
    "accesibilidad": "abierta",
    "visualizacion": "PDF;visor propio",
    "descarga": "sí",
    "ocr": "sí",
    "api": "no",
    "licencia": "dominio público",
    "calidad_digitalizacion": "media",
    "interoperabilidad": "OAI-PMH",
    "institucion": "Universidad de la Républica Uruguay",
    "tipo_institucion": "universidad",
    "financiamiento": "académico",
    "temas_dominantes": "sociedad;literatura;arte",
    "contacto": "anaforas@fic.edu.uy",
    "fecha_relevamiento": "2026-07-01",
    "estado_enlace": "activo",
    "notas": "Colección de publicaciones periódicas uruguayas. Acceso a través de repositorio DSpace..",
    "images": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-013.webp"
    ],
    "thumbnails": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-013-thumb.webp"
    ]
  },
  {
    "id": "REP-014",
    "nombre": "Revistas Culturales de Amérca Latina - Ibero-Amerikanisches Institut",
    "nombre_alternativo": "IAI",
    "url": "https://digital.iai.spk-berlin.de/viewer/collections/lateinamerikanische-kulturzeitschriften/",
    "url_alternativa": "https://www.iai.spk-berlin.de/",
    "tipo": "colección",
    "alcance": "general",
    "especializacion": "",
    "tipos_publicacion": "revistas",
    "volumen_aprox": "244 títulos",
    "periodo_desde": "1880",
    "periodo_hasta": "1930",
    "idiomas": "español;portugués",
    "ciudad": "Berlín",
    "pais": "Alemania",
    "latitud": "52.5200",
    "longitud": "13.4050",
    "cobertura_geografica": "Latinoamérica",
    "accesibilidad": "abierta",
    "visualizacion": "PDF;IIIF;Mirador;Goobi Viewer",
    "descarga": "sí",
    "ocr": "sí",
    "api": "no",
    "licencia": "dominio público",
    "calidad_digitalizacion": "alta",
    "interoperabilidad": "IIIF",
    "institucion": "Ibero-Amerikanisches Institut (Instituto Iberoamericano)",
    "tipo_institucion": "biblioteca",
    "financiamiento": "público",
    "temas_dominantes": "sociedad;literatura",
    "contacto": "Formulario",
    "fecha_relevamiento": "2026-07-01",
    "estado_enlace": "activo",
    "notas": "Colección de revistas de Argentina, Brasil, Chile, Colombia, Cuba, Ecuador, Perú y Puerto Rico",
    "images": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-014.webp"
    ],
    "thumbnails": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-014-thumb.webp"
    ]
  },
  {
    "id": "REP-015",
    "nombre": "El Kiosko - Hemeroteca Histórica Digital de la Izquierda",
    "nombre_alternativo": "NA",
    "url": "https://www.marxists.org/espanol/tematica/kiosko/",
    "url_alternativa": "NA",
    "tipo": "colección",
    "alcance": "específico",
    "especializacion": "revistas de izquierda",
    "tipos_publicacion": "revistas",
    "volumen_aprox": "~120 títulos",
    "periodo_desde": "",
    "periodo_hasta": "",
    "idiomas": "español",
    "ciudad": "NA",
    "pais": "NA",
    "latitud": "NA",
    "longitud": "NA",
    "cobertura_geografica": "Internacional",
    "accesibilidad": "abierta",
    "visualizacion": "PDF",
    "descarga": "sí",
    "ocr": "parcial",
    "api": "no",
    "licencia": "dominio público",
    "calidad_digitalizacion": "media",
    "interoperabilidad": "desconocida",
    "institucion": "Marxist Internet Archive",
    "tipo_institucion": "otra",
    "financiamiento": "desconocido",
    "temas_dominantes": "política",
    "contacto": "juanf@marxists.org",
    "fecha_relevamiento": "2026-07-01",
    "estado_enlace": "activo",
    "notas": "Colección de publicaciones periódicas de izquierda latinoamericanas y otras editadas en China, la extinta Unión Soviética y Estados Unidos.",
    "images": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-015.webp"
    ],
    "thumbnails": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-015-thumb.webp"
    ]
  },
  {
    "id": "REP-016",
    "nombre": "Revistas literarias y culturales colombianas",
    "nombre_alternativo": "NA",
    "url": "https://hdl.handle.net/10495/29648",
    "url_alternativa": "https://bibliotecadigital.udea.edu.co/collections/7122e49a-95c2-4ecc-aa61-4b49350343d3",
    "tipo": "colección",
    "alcance": "específico",
    "especializacion": "",
    "tipos_publicacion": "revistas",
    "volumen_aprox": "12 títulos",
    "periodo_desde": "1881",
    "periodo_hasta": "1941",
    "idiomas": "español",
    "ciudad": "Medellín",
    "pais": "Colombia",
    "latitud": "6.2442",
    "longitud": "-75.5812",
    "cobertura_geografica": "Colombia",
    "accesibilidad": "abierta",
    "visualizacion": "PDF;FLIP",
    "descarga": "sí",
    "ocr": "sí",
    "api": "no",
    "licencia": "dominio público",
    "calidad_digitalizacion": "alta",
    "interoperabilidad": "OAI-PMH",
    "institucion": "Universidad de Antioquia",
    "tipo_institucion": "universidad",
    "financiamiento": "académico",
    "temas_dominantes": "sociedad;literatura",
    "contacto": "bibliotecadigital@udea.edu.co",
    "fecha_relevamiento": "2026-07-01",
    "estado_enlace": "activo",
    "notas": "Colección de revistas colombianas editadas en Medellín, Bogotá y Londres.",
    "images": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-016.webp"
    ],
    "thumbnails": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-016-thumb.webp"
    ]
  },
  {
    "id": "REP-017",
    "nombre": "Hemeroteca Digital Histórica- Biblioteca Virtual Banco de la República",
    "nombre_alternativo": "NA",
    "url": "https://babel.banrepcultural.org/digital/collection/p17054coll26",
    "url_alternativa": "NA",
    "tipo": "hemeroteca digital",
    "alcance": "general",
    "especializacion": "",
    "tipos_publicacion": "revistas;periódicos",
    "volumen_aprox": "759 títulos",
    "periodo_desde": "1785",
    "periodo_hasta": "1963",
    "idiomas": "español",
    "ciudad": "Bogotá",
    "pais": "Colombia",
    "latitud": "4.7110",
    "longitud": "-74.0721",
    "cobertura_geografica": "Colombia",
    "accesibilidad": "abierta",
    "visualizacion": "PDF;IIIF;Visor propio",
    "descarga": "sí",
    "ocr": "sí",
    "api": "no",
    "licencia": "dominio público",
    "calidad_digitalizacion": "alta",
    "interoperabilidad": "IIIF",
    "institucion": "Banco de la República",
    "tipo_institucion": "biblioteca",
    "financiamiento": "privado",
    "temas_dominantes": "sociedad;política;literatura;cultura",
    "contacto": "Formulario",
    "fecha_relevamiento": "2026-07-01",
    "estado_enlace": "activo",
    "notas": "Colección de revistas colombianas",
    "images": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-017.webp"
    ],
    "thumbnails": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-017-thumb.webp"
    ]
  },
  {
    "id": "REP-018",
    "nombre": "Hemeroteca Digital - Biblioteca Nacional de Colombia",
    "nombre_alternativo": "NA",
    "url": "https://catalogoenlinea.bibliotecanacional.gov.co/client/es_ES/bd/?rm=PRENSA+COLOMBI0%7C%7C%7C1%7C%7C%7C4%7C%7C%7Ctrue",
    "url_alternativa": "NA",
    "tipo": "hemeroteca digital",
    "alcance": "general",
    "especializacion": "",
    "tipos_publicacion": "revistas;periódicos;boletines",
    "volumen_aprox": "~1178",
    "periodo_desde": "1772",
    "periodo_hasta": "2018",
    "idiomas": "español",
    "ciudad": "Bogotá",
    "pais": "Colombia",
    "latitud": "4.7110",
    "longitud": "-74.0721",
    "cobertura_geografica": "Colombia",
    "accesibilidad": "abierta",
    "visualizacion": "PDF;navegador",
    "descarga": "sí",
    "ocr": "parcial",
    "api": "no",
    "licencia": "dominio público; derechos reservados",
    "calidad_digitalizacion": "alta",
    "interoperabilidad": "OAI-PMH",
    "institucion": "Biblioteca Nacional de Colombia",
    "tipo_institucion": "biblioteca nacional",
    "financiamiento": "público",
    "temas_dominantes": "sociedad;política;literartura;cultura",
    "contacto": "Formulario",
    "fecha_relevamiento": "2026-07-01",
    "estado_enlace": "activo",
    "notas": "Colección de publicaciones periódicas colombianas e índices análiticos de algunas de ellas.",
    "images": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-018.webp"
    ],
    "thumbnails": [
      "https://srsergiorodriguez.github.io/revistas-culturales-20/media/files/imagenes-repositorios/REP-018-thumb.webp"
    ]
  }
];